### ISSUE TITLE
Requests (authorize, refresh) stop working when app is stale

### ISSUE THREAD

**Issue by spsaucier** [FormidableLabs/react-native-app-auth#359] opened 2019-07-15 19:12 UTC
## Issue
**Everything works perfectly** after a new android build. However, if the app has been left open for a while (e.g. opening it up the next day):
* `authorize` calls no longer bring up a webview at all, even if I call it repeatedly. There are no network requests made. The promise never returns.
* `refresh` acts the same way - no response, the promise never returns, no network requests are made.
* I'm not sure whether `revoke` does the same thing, because it's hard to test after a period of inactivity because of token expiration.

I can temporarily fix this issue locally simply by re-building the application. However, I don't know of a fix on a deployed app. This app is Android-only at the moment.

I'm using Okta for authentication, and my config is something like this:
```
const config = {
  clientId: "asdfasdfasdf",
  issuer: "https://subdomain.okta.com/oauth2/asdfasdf",
  redirectUrl: "omt://callback",
  scopes: ["openid", "profile", "email", "offline_access"]
}
```

---

## Environment

* **Your Identity Provider**: `Okta`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No.

**Comment by kadikraman** [comment] 2019-07-15 19:41
Hi @spsaucier 👋 - which versions of this library and React Native are you using?

**Comment by spsaucier** [comment] 2019-07-15 19:45
@kadikraman:
* `react-native-app-auth@4.4.0`
* `react-native@0.59.8`

**Comment by kadikraman** [comment] 2019-07-15 20:51
Alright, I'm going to try to recreate the error. I've created an example app with `react-native-app-auth@4.4.0` and `react-native@0.59.8`, launched it on an Android phone with `react-native run-android`, and logged with my demo Okta account.

I'll try to open the app again tomorrow morning and try to log in to see if I am able to reproduce your error.

**Comment by kadikraman** [comment] 2019-07-15 20:55
If you wouldn't mind trying something in the meanwhile - could you install `react-native-app-auth@4.3.0`. The last major change to the Android was [this pr](https://github.com/FormidableLabs/react-native-app-auth/pull/289) which could have something to do with the issue.

**Comment by spsaucier** [comment] 2019-07-15 21:13
Thanks @kadikraman, I've upgraded to 4.4.0, but the issue remains.

**Comment by kadikraman** [comment] 2019-07-15 21:52
My bad - could you try [v4.3.1](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v4.3.1)?

**Comment by spsaucier** [comment] 2019-07-15 21:55
@kadikraman Actually, that appears to have fixed it 🎊 - I'll see if it's still fixed in the morning. Thanks!

**Comment by spsaucier** [comment] 2019-07-16 12:12
Well, unfortunately I'm still experiencing the issue. I think it appeared resolved last night because it rebuilt after switching package versions.

**Comment by kadikraman** [comment] 2019-07-16 13:42
That's a shame. I failed to reproduce it overnight without prefetching configuration, but I tried to authenticate with prefetching - I set up the app 5 hours ago, and tried just now, and I was still unable to reproduce your error.

This is my configuration object:

```
const config = {
  warmAndPrefetchChrome: true,
  issuer: 'https://dev-351681.oktapreview.com/oauth2/default',
  clientId: '0oafl6mk4oEbnqtKK0h7',
  redirectUrl: 'com.oktapreview.dev-351681:/callback',
  scopes: ['openid', 'profile']
};
```

and I'm calling `prefetchConfiguration(config);` in `App.js` onLoad - is this any different from your setup?

**Comment by spsaucier** [comment] 2019-07-16 13:56
I have the same issue when using your config directly.
I had not been prefetching -- `prefetchConfiguration` does not resolve and gives me a warning:
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'apply' of undefined
```

**Comment by kadikraman** [comment] 2019-07-16 14:31
Huh. I didn't clarify, my project is built on `react-native@0.59.8` and `react-native-app-auth@4.4.0`.

**Comment by spsaucier** [comment] 2019-07-16 17:22
I think some of my troubles have been exacerbated by DNS issues in my emulator, which I've fixed now. I'll re-test this issue on `4.3.1` in the morning.

**Comment by spsaucier** [comment] 2019-07-16 19:13
The issue seems to be persisting on a stale build even now, with DNS resolved & using `4.3.1`, and once again, it is resolved by running `react-native run-android`.

**Comment by kadikraman** [comment] 2019-07-17 09:41
I've just tried this again on an emulator I last used to log on yesterday, and had no issues.

Are you able to reproduce it at all using any another device on another network / laptop?

**Comment by spsaucier** [comment] 2019-07-17 11:40
Yes, my team has experienced it on several laptops as well as tablets with the installed apk. I've experienced it on different networks as well, though I haven't tested that as thoroughly yet.

**Comment by spsaucier** [comment] 2019-07-17 12:16
Interesting -- when I tried again this morning, it finally _did_ resolve -- it just took about 4 minutes to do so:
<img width="538" alt="Screen Shot 2019-07-17 at 8 14 48 AM" src="https://user-images.githubusercontent.com/596143/61374710-0a57bd00-a86b-11e9-88b4-310b0f5870d0.png">
That makes me more suspicious of the network.

**Comment by spsaucier** [comment] 2019-08-06 16:24
Any further ideas on why this could be happening?
I haven't recently seen it resolve after any amount of time, and all react-native-app-auth actions fail about half the time. It is happening on Android physical devices and the emulator (the app is Android-only). There are no network requests being made, as far as I can tell. The app is not frozen.

**Comment by spsaucier** [comment] 2019-08-06 17:24
I tried your config again, and that again made no difference.
I've also now switched to `@okta/okta-react-native` instead of `react-native-app-auth` and the same thing seems to be occurring. No requests made, no resolution to the request. Maybe it has to do with some obscure configuration on this particular Android project?

**Comment by spsaucier** [comment] 2019-08-08 16:50
@kadikraman Alright, some progress in debugging the `authorize` call here:
* If I don't include a `serviceConfig`, `authorize` gets to [RNAppAuthModule.java#L183](https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L183) and never calls the callback function.
* If I _do_ include a `serviceConfig`, (which I got from [here](https://cfahome.oktapreview.com/oauth2/ausc6e4sj2fnPnQ670h7/.well-known/openid-configuration)), `authorize` gets down to [RNAppAuthModule.java#L168](https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L168) but never enters into the `authorizeWithConfiguration` function. It then loops back and runs `authorize` again endlessly.

**Comment by spsaucier** [comment] 2019-08-08 17:23
For case 2 above, I've switched the property names from snake_case to camelCase, and it appears to be working correctly!

If that holds, it seems to indicate that the issue is in the `AuthorizationServiceConfiguration.fetchFromUrl` method of `net.openid.appauth`, which periodically never calls the callback. Perhaps there is an uncaught error occurring in there in those instances.

**Comment by Highspeed7** [comment] 2019-08-12 09:17
@kadikraman Any update on this? I too am experiencing something similar to this, though the webview for me shows... the promise is never resolved/rejected and the app just hangs.

**Comment by spsaucier** [comment] 2019-08-13 18:07
@Highspeed7 I'm seeing that with certain users as well - it is a separate issue from mine above though, as the login prompt does appear, but submitting it doesn't resolve the promise.

**Comment by Jay-A-McBee** [comment] 2022-01-18 21:53
:wave: hey everyone - it sounds like spsaucier was able to come to a resolution on this. Closing this out.

**Closed by Jay-A-McBee** 2022-01-18 21:53 UTC
