### ISSUE TITLE
Do we have any way to update prefersEphemeralWebBrowserSession property in order to avoid iOS user alert?

### ISSUE THREAD

**Issue by prasanth1216** [FormidableLabs/react-native-app-auth#634] opened 2021-05-18 07:10 UTC
## Query

As we know by using ASWebAuthenticationSession will automatically present a mandatory dialog box asking the user to give explicit consent for accessing the website’s data. In iOS iOS 13 may omit the dialog by configuring ASWebAuthenticationSession for a private session by setting  **prefersEphemeralWebBrowserSession**  property.
Currently, do we have any provision access and update this property?

---

## Environment

* **Are you using Expo?** No
* **React Native Version** ^6.2.0
* **react-native-app-auth** 0.62.0

**Comment by jpdriver** [comment] 2021-07-08 16:56
duplicate of https://github.com/FormidableLabs/react-native-app-auth/issues/428#issuecomment-650801109

**Closed by jpdriver** 2021-07-08 16:56 UTC
