### ISSUE TITLE
iOS: Popup asking for permission to authorize closing after a couple of milliseconds in Release mode, from then on, authorization will never start again

### ISSUE THREAD

**Issue by the-smart-home-maker** [FormidableLabs/react-native-app-auth#525] opened 2020-07-05 08:48 UTC
## Issue

I am using React Native AppAuth with AWS Cognito and everything works well in Debug mode. Now I have sent a first version of my app to Testflight and realized that in Release mode there seems to be a problem. 

Usually in Debug mode when I open my app and start the authorize command, a popup opens, asking for permission to redirect to my identity provider AWS Cognito as expected.  This popup stays open until I either cancel or allow for redirecting to Cognito. 

When in Release mode, unfortunately the popup asking for permission to authorize is opening but again closing after a couple of milliseconds - too quick for the user to even be able to make a choice. From then on, the app seems to be stuck somewhere and I can not use it. Also closing and reopening the app won't help - the popup will not even show up any more.

Actually I observed, that for the very first time authorizing on the device in Release mode, it worked fine but since the access token got invalid for the first time, I was  ever able to authorize again.

I am trying to get some more log data by activating log level info also in release mode. If I find some more information, I will update this issue.

Is this behavior a known issue? 

Update: I was able to get the actual error message via an alert window. The error message says:
"Failed to log in. The operation couldn't be completed (org.openid.appauth.general error -3.)"

Update: I was now able to see this error occasionally in debug mode - but there I am able to just refresh and then everything works fine again. In Release Mode that doesn’t work.

Did anyone experience this issue as well? I saw this issue was caused by an incompatibility with iOS 13 beta but I think that should be fixed by now. I am really clueless in what to do now...

Update: I have now tested the behavior on a different iPhone, an iPhone 7 instead of an iPhone XS. Same problem here - in Release mode the popup disappears right after showing up and will not come back even after restarting the app...

---

## Environment

* **Your Identity Provider**: AWS Cognito
* **Platform that you're experiencing the issue on**: iOS 13.5.1, Android not tested
* **Are you using Expo?** no
* **React Native Version** 0.62.2 
* **AppAuth Version ** 1 2.0

**Comment by the-smart-home-maker** [comment] 2020-07-11 08:54
Am I the only person experiencing this issue?

**Comment by kadikraman** [comment] 2020-07-12 09:06
Is this happening on iOS 13.5.1 only? Can you reproduce it in our example app?

**Comment by the-smart-home-maker** [comment] 2020-07-12 13:20
I just released to TestFlight with iOS 13.5.1 so I don't know what the behavior would have been with iOS < 13.5.1. But at least this issue never popped up before (I had apps in Release mode with 13.x that worked well) so it might be specific to 13.5.1.

If it would want to reproduce this with your example app, I would need to push the example app to TestFlight...

**Comment by kadikraman** [comment] 2020-07-12 14:43
Oh, TestFlight is definitely not necessary, we'd just want to try and test the same app bundle that'd get submitted TestFlight and get the error to happen consistently. You said it happens only on release - if so, then building the app locally in release mode and installing on device should do it. I'm trying to determine whether this is something to do with your IDP or if it's _any_ IDP, and figure out some reliable steps to reproduce :)

Originally you said you've had the same issue occasionally during development as well - can you reproduce it reliably, or is it more like it happens ~10% of the time, but randomly?

**Comment by the-smart-home-maker** [comment] 2020-07-12 16:43
Thanks, ok I will try that.

Yes I've seen the issue in debug mode sporadically in about 5-10% of runs but in that case it is always possible to just refresh and then it's gone - in Release mode that won't help.

**Comment by srinadh-k** [comment] 2020-07-13 20:19
Yes, 
We are also facing same issue for iOS but if we replace our old AppAuth Podfile modules we are not facing this issue. Looks like something issue with the latest version. 

Please let me know, if anyone have a solution.

**Comment by DhanrajNaik** [comment] 2020-07-29 17:20
Anyone got fix for this issue??

**Comment by devproivansurzhenko** [comment] 2020-08-11 12:55
@DhanrajNaik Did you have a chance to determine the affected scope?

In my story, i have only one user reported similar issue. Unfortunately, I am unable to talk to him and ask for extra info.
So, the main hurdle for me is impossibility to reproduce on my end.

**Comment by the-smart-home-maker** [comment] 2020-08-17 09:13
Please have a look at the following issue:

https://github.com/openid/AppAuth-iOS/issues/447

I guess this is the underlying actual problem so it might not have to do with your AppAuth wrapper but with the original AppAuth library or even with an Apple-side bug if following the discussion in the forementioned issue...

**Comment by Jay-A-McBee** [comment] 2022-02-08 20:40
I setup up an AWS Cognito user pool and App Client (without a secret) and ran a release build (xcode 12.5.1) on iOS 13 of the example app without issue. Cannot reproduce - closing this out.

**Closed by Jay-A-McBee** 2022-02-08 20:40 UTC
