### ISSUE TITLE
[Android] Does not compile

### ISSUE THREAD

**Issue by adambutler** [FormidableLabs/react-native-app-auth#325] opened 2019-06-18 12:37 UTC
## Issue

As of today, our app does not compile. This seems to have something to do with Google a new version of their Play Service. As I understand it some libraries need to be updated to account for this.

More information can be found at https://github.com/facebook/react-native/issues/25293#issuecomment-503045776

---

## Environment

* **Your Identity Provider**: n/a
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** No

**Comment by kelset** [comment] 2019-06-18 12:43
👋 there!

I was looking into the `build.gradle` -> https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/build.gradle

and it doesn't seem that we have any dependency to google's play services directly. So it's likely that it's another library that is causing your issue.

Or, can you provide a repro so that we can take a closer look?

**Comment by adambutler** [comment] 2019-06-18 13:20
@kelset Thank you for your quick response. Whilst addressing the issues that I previously linked to I changed my `gradle.properties` file to include:

```
android.useAndroidX=true
android.enableJetifier=true
```

I believe this is the actual cause of this library not compiling correctly and raises the error:

```
package android.support.annotation does not exist
```

I assumed this may have related to the same root cause but may be mistaken. I'll continue to dig and will close this issue shortly if the changes required to get our the app building is _actually_ dependent on this configuration.

**Comment by mortendybdal** [comment] 2019-06-18 13:46
Hi @adambutler 
I'm having the exact same issue - I'd like to hear what you find out:-)

**Comment by castillobgr** [comment] 2019-06-18 13:56
I am also getting similar errors. In my case, when I put 
```properties
android.useAndroidX=true
android.enableJetifier=true
```
in `gradle.properties`, I get:
```sh
/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:383: error: cannot find symbol
            public void onTokenRequestCompleted(@Nullable TokenResponse response, @Nullable AuthorizationException ex) {
                                                                                   ^
  symbol: class Nullable
```

@adambutler this is because `react-native-app-auth` still depends on the Android support libs, while other libs and new projects depend on AndroidX, and both are incompatible with one another.

**Comment by kelset** [comment] 2019-06-18 14:17
It seems to me, that this is related to - maybe - Android Studio automatically updating your gradle dependencies?

It's an annoying feature that it has.

Again, can anyone please provide a repro?

**Comment by kadikraman** [comment] 2019-06-18 14:50
I wasn't able to reproduce this with our example app. Based on @castillobgr 's comment, I suspect it's either one of the other libraries depending on the new Google Services patch, or a conflict between the config of this library and another dependency. Without knowing what the other dependencies are, this is hard to debug.

```bash
git clone git@github.com:FormidableLabs/react-native-app-auth.git
cd react-native-app-auth/Example/Latest
yarn
react-native run-android
```

I would greatly appreciate a reproduction of the error. You can use the example app as a starting point.

**Comment by castillobgr** [comment] 2019-06-18 15:21
In our case, the problem was in another lib. We updated it and removed the androidx properties in `gradle.properties`, (which got appauth compiling again). See https://stackoverflow.com/a/56646765

**Comment by kelset** [comment] 2019-06-18 15:27
ok, it seems that we can safely close this for now then.

**Closed by kelset** 2019-06-18 15:27 UTC
