### ISSUE TITLE
Refreshing with performActionWithFreshTokens

### ISSUE THREAD

**Issue by davidbani** [FormidableLabs/react-native-app-auth#318] opened 2019-06-05 03:38 UTC
Does the `refresh` method use `performActionWithFreshTokens`? Any reason why `refresh` doesn't return the same token if it hasn't expired? Example: current accessToken is "eyJ0eX###". calling `refresh` method should return "eyJ0eX###" again  if access token has not expired. It seems to return new tokens every time `refresh` is called.

Is this not the case?

https://openid.github.io/AppAuth-iOS/docs/latest/interface_o_i_d_auth_state.html#a0e7b2ea13d035b37cf48ddfd95065e9d

**Comment by Jay-A-McBee** [comment] 2022-01-18 19:36
:wave: hey @davidbani -  The refresh method does not use `performActionWithFreshTokens` - it uses the `performTokenRequest` method - https://openid.github.io/AppAuth-iOS/docs/latest/interface_o_i_d_authorization_service.html#aedf588e591cd38c97b222b58522fc758.  

If the id token is still valid, is there a need to call `refresh` proactively?  Closing this out because it seems like this is expected behavior for the explicit `refresh` method.

**Closed by Jay-A-McBee** 2022-01-18 19:36 UTC
