### ISSUE TITLE
revoke requires Authorization in header

### ISSUE THREAD

**Issue by cribcutkiran** [FormidableLabs/react-native-app-auth#70] opened 2018-03-10 19:25 UTC
According to the Oauth spec (https://tools.ietf.org/html/rfc7009), token revocation requires an Authentication header, but it is not being added:
https://github.com/FormidableLabs/react-native-app-auth/blob/727f5965bd66e7fc67f8cfbe3d192e20b67920bb/index.js#L126

Using sendClientId=true, doesn't help since it is added to the body and not to the header. I have been unable to get revoke() to work with Okta, and I suspect this is why.

**Comment by jevakallio** [comment] 2018-03-12 12:31
Thanks for this issue. The team is a little busy this week. If you end up fixing this yourself, would ❤️ a PR!

**Comment by mraible** [comment] 2018-03-15 18:34
I can confirm that this is an issue.

**Comment by tgearig** [comment] 2018-06-26 17:46
Is there an update on this issue? It's still a problem. Is it slated to be addressed in the near future?

**Comment by kadikraman** [comment] 2018-06-27 09:36
What makes you think it's not working? Calling the `/revoke` endpoint returns a `200 OK`.

I've just created an Okta dev account and tried this. I get `200 OK` as a result from Okta, and the following in the Okta console:

<img width="1080" alt="screen shot 2018-06-27 at 10 33 13" src="https://user-images.githubusercontent.com/6534400/41965873-96ba2cb0-79f5-11e8-8109-9a5b450fe4f7.png">

Closing as I don't think it's an issue, but please reopen with steps to reproduce if you think it is.

**Closed by kadikraman** 2018-06-27 09:36 UTC

**Comment by mraible** [comment] 2018-09-28 22:54
Is /revoke supposed to fully log you out of the IdP? If so, it's not working because when I go back to the app after logging out and click "Authorize" again, I'm not prompted to log in. I know this is how SSO is supposed to work, but I expected `/revoke` to cause it so I have to log in again.

**Comment by kadikraman** [comment] 2018-10-12 11:40
@mrsteveheyes It should work on Android. See [this comment from AppAuth-Android](https://github.com/openid/AppAuth-Android/issues/289#issuecomment-340068494) that explains it in detail.

**Comment by mrsteveheyes** [comment] 2018-10-12 14:06
🤔 Hmmm. So here is my set up and what I'm expecting to happen?

• I have a RN Android app signing in via OAuth to a Rails app using Doorkeeper with Devise.
• I expect that when ever I call `authorize` in my RN Android app with `prompt:'login'` in the config (under `additionalParameters`) then it should _always_ bring up a form form me to sign into.
• Currently it just brings up the CustomTab view, loads a game and then goes straight onto the screen it should be redirected to; thus logging me in.

I hope that makes sense.

**Comment by mrsteveheyes** [comment] 2018-10-12 15:23
Great, thanks for outlining this. I'll check my setup, but I'm not sure it will do that. Maybe able to make it do that some how though...
