### ISSUE TITLE
When calling authorize() with credentials cached, android sometimes gets stuck on white screen (page load)

### ISSUE THREAD

**Issue by SocialBrothersDEV** [FormidableLabs/react-native-app-auth#481] opened 2020-03-12 08:44 UTC
## Issue
First of all i want to thank the contributors of this library for their work and effort, it really helped me with my current project.

When the device has logged in once the following `authorize()` calls will not require a password again since it's cached or something. On iOS this works perfect, but on android i sometimes get stuk on a white screen. The authorization page just doesn't load. When i cancel the chrome modal and retry, it eventually works. Does anyone know a solution for this, or is it just a bug in the library?

Thanks in advance.

---

## Environment

* **Your Identity Provider**: `Keycloak`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** `No`

**Comment by aeirola** [comment] 2020-07-01 04:55
We've experienced some similar issues, which was caused by a security feature in Chrome where it doesn't perform automatic redirects to native applications. This means that the authentication flow needs to contain some step where the user actively presses a button to perform the navigation.

See https://stackoverflow.com/a/41882732 for some more discussion on the topic.

**Comment by Jay-A-McBee** [comment] 2022-01-24 21:06
:wave: hey @SocialBrothersDEV - as aeirola stated this is a security feature of the Chrome browser. A common solution that I have come across is to have an interstitial html page used as your redirectURI. This page will provide the button for user interaction. 

On redirect, the interstitial page will open in the browser  used for authentication- the url will contain all the relevant auth params. The user will click the button  on this page and trigger navigation to the custom url scheme registered in your app. 
It's not a perfect solution as it requires an additional web page to be hosted/maintained, but it is the suggested solution put forth by AppAuth maintainers.

See [AppAuth-Android issue thread and comment](https://github.com/openid/AppAuth-Android/issues/527#issuecomment-640904798).

Closing this out as the issue is third-party related and the solution is outside of the scope of this library.

**Closed by Jay-A-McBee** 2022-01-24 21:06 UTC
