### ISSUE TITLE
Crash caused by java.lang.NullPointerException: dataIntent must not be null (potentially related: New chrome Version)

### ISSUE THREAD

**Issue by KeiShadow** [FormidableLabs/react-native-app-auth#237] opened 2019-02-05 16:20 UTC
## Issue
Hello, my application crashed with latest chrome browser( 72.0.3626.76)
In app i detected if the chrome is installed if yes the redirect url is change for page after the correct  login the ids server will redirect user to page where is a button with required params for redirect back to APP. The login worked very well since last chrome update. The another browser working good.

Log: 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: **secret**, PID: 1804
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {**secret**/**secret**.MainActivity}: java.lang.NullPointerException: dataIntent must not be null
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)

## Environment

- **Your Identity Provider**: dentityServer 4 
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by sraka1** [comment] 2019-02-06 14:26
Looks like this is also related to my comment in #130 and is getting more and more frequent? Maybe a newer Chrome is somehow the problem here?

@kadikraman have you had this issue occur as well?

**Comment by kadikraman** [comment] 2019-02-06 17:36
Hi @sraka1 - I haven't had the chance to investigate this yet, but it's on my backlog.

**Comment by sraka1** [comment] 2019-03-19 12:46
@kadikraman could you please rename this issue into "Crash caused by java.lang.NullPointerException: dataIntent must not be null". I don't think the version of Chrome (or any other browser) is to blame here...

**Comment by kadikraman** [comment] 2019-03-31 16:40
Thanks for the tip, @sraka1 - the new Chrome version may be a coincidence in this case.

**Comment by Jay-A-McBee** [comment] 2022-02-03 19:24
Closing this out - should be fixed by https://github.com/FormidableLabs/react-native-app-auth/pull/352.

**Closed by Jay-A-McBee** 2022-02-03 19:24 UTC
