### ISSUE TITLE
iOS issue: undefined is not an object (evaluating 'RNAppAuth.authorize') error" and "Cannot read property authorize of undefined

### ISSUE THREAD

**Issue by thanmaic** [FormidableLabs/react-native-app-auth#524] opened 2020-07-02 07:56 UTC
## Issue
I am facing this issue "undefined is not an object (evaluating 'RNAppAuth.authorize') error" and "Cannot read property authorize of undefined". Could anyone help me resolve this. 

---

## Environment

* **Your Identity Provider**: OKTA
* **Platform that you're experiencing the issue on**: iOS 
* **Are you using Expo?** NO

ReactNative version: 0.51.0
react-native-app-auth: "^3.1.0"

**I have tried also v4 and v5 of this library, but still get the same error.**

**Surprisingly the same setup and code was working about a year ago. And now I needed to add/change some things so tried now. But it breaks with the above mentioned errors in iOS.**

## Steps that i have followed

1. npm install react-native-app-auth --save
2. react-native link react-native-app-auth

Using Cocopods,
1. Added pod 'AppAuth', '>= 0.94' in pod file. Also tried pod 'AppAuth', '1.2.0'
2. pod install.

Using Manually,
1. Added RNAppAuth.xcodeproj to Libraries
2. And included libRNAppAuth.a to project's Build Phases ➜ Link Binary With Libraries

Also followed steps of:
Register redirect URL scheme, Define openURL callback in AppDelegate and Integration of the library with a Swift iOS project
as mentioned in the setup section.

Tried both using cocopods and manually to add the library, but still it's the same error. Please find attached screenshots. 

**I have have been stuck with this since many days, and no solution in other issues also seem to work.** 
I would be grateful if anyone here could help me resolve this issue at the earliest.

Thank you.

<img width="1680" alt="Screenshot 2020-07-01 at 8 57 49 PM" src="https://user-images.githubusercontent.com/50735542/86319795-f7dcbc00-bc52-11ea-9bdb-5c383d069dd2.png">
<img width="1680" alt="Screenshot 2020-07-01 at 12 55 48 PM" src="https://user-images.githubusercontent.com/50735542/86319822-02975100-bc53-11ea-9e1c-ba5c5a1c83b3.png">

**Comment by jpdriver** [comment] 2020-07-04 09:29
hi @thanmaic -- this will be an issue linking the native module with your React Native project.

can you confirm exactly which linking method you are trying to use? (`react-native link` / CocoaPods / Carthage / etc.)

i know you've already tried several different ones while trying to resolve this -- but i guess my question is do you know which linking method it originally used when it was working?

as this is an older project, i would recommend trying to stick to whichever method that was if possible..

**Comment by thanmaic** [comment] 2020-07-04 11:34
Steps followed:
1. npm install react-native-app-auth@^3.1.0 --save
2. react-native link react-native-app-auth
3. cocopods - pod install  (pod 'AppAuth', '>= 0.94')

I don't know which linking method was originally used when it was working since the guy who build the functionality has left.

So could you please suggest me a correct method to follow and get the application running without this error?
Thanks

**Comment by kadikraman** [comment] 2020-07-07 07:57
Hi @thanmaic - it's possible that something has gone wrong with the upgrade from pre 0.59 -> 0.6x, both 59 to 60 and 60 to 61 were very tricky upgrades, especially 0.60, since that added autolinking.

If you are on 0.60 or higher, you should to use v5.x of this library.

From a fresh install on RN 0.60 ad higher, the following instructions are guaranteed to work:

1. Install the latest version of the library
```
npm install react-native-app-auth --save
```

2. Install the AppAuth Pods (no need to do a linking step)
```
cd ios && pod install && cd ..
```

That's it.

If that doesn't work, there might be some existing code that conflicts with your current solution. If you haven't already, check out the [example app](https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example) in this repo and compare the Podfiles - notice that ours doesn't have any reference of AppAuth whereas if you look at the [Podfile.lock](https://github.com/FormidableLabs/react-native-app-auth/blob/master/Example/ios/Podfile.lock) (this is similar to a `packege-lock.json` for npm and should never be edited manually) you can see that the dependency has been installed using autolinking. What happend in step 2 when you do `pod install` is that [our podspec](https://github.com/FormidableLabs/react-native-app-auth/blob/master/react-native-app-auth.podspec) is inspected and the required dependency `'AppAuth', '1.2.0'` is installed.

I hope this helps.

**Comment by thanmaic** [comment] 2020-07-07 08:27
Hi @kadikraman , I understand you have mentioned it to be working for 0.60 RN and higher. But the application in which i am using is an old one 0.51.0. Hence using v3.1 version on react-native-app-auth. I don't have much time to upgrade the RN version at present and this needs to be fixed on 0.51 RN only. 
Doesn't react-native-app-auth support for RN version 0.51.0? But it works on Android and i have this issue only on iOS.
Any help on how to fix it on same version would be great. 
Thanks.

**Comment by kadikraman** [comment] 2020-07-07 08:41
Oh! My apologies! I realise now you wrote `0.51.0`. I misread this as `0.61.0` 🤦‍♀️   

I'll try and reproduce this. Was the original implementation using Carthage, Cocoapods or manual linking for the native dependency?

**Comment by thanmaic** [comment] 2020-07-07 08:46
It was using cocopods. Also tried Manual liking. Both resulted in the same error.

**Comment by kadikraman** [comment] 2020-07-07 09:10
I tried recreate this, but looks like I can't even run `RN 0.51.0` locally, it seems to have issues with the my version of XCode.

I'm not sure what I can do to help you at this point. The error you are getting - "cannot read property authorize of undefined" - means that the native part of the library didn't get included properly, but it's very difficult for me to determine why.

I'm sure you did, but just to sanity check - make sure you are rebuilding the app with `react-native run-ios` or via Xcode after adding the native dependency.

If you want to use `v3.1.0`, you could review the instructions for that tag, since there used to be additional configuration for iOS https://github.com/FormidableLabs/react-native-app-auth/tree/v3.1.0

You could try using `v4.4.0` - this is what I would do I think, since it's the latest version that should be supported for the version of React Native you're on, and the iOS setup was simplified. The `v4.4.0` instructions are here: https://github.com/FormidableLabs/react-native-app-auth/tree/v4.4.0

**Comment by thanmaic** [comment] 2020-07-07 09:47
ok will look into those and get back..thanks

**Comment by thanmaic** [comment] 2020-07-07 16:54
@kadikraman I followed the exact same steps as mentioned here https://github.com/FormidableLabs/react-native-app-auth/tree/v4.4.0#setup. I also made sure to have the same react-native-app-auth version(v4.1.1) and podfile( pod ‘AppAuth’, ‘>=0.94’) as in the example mentioned here https://github.com/FormidableLabs/react-native-app-auth/tree/v4.4.0/Example/iOSPodsExample.

**ReactNative version: 0.51.0
RNAppAuth version: ^4.1.1
Cocopods: (pod ‘AppAuth’, ‘>=0.94’)
Steps followed exactly same as in the v4.4.0 docs (setup section)**

This application is working fine in Android, but I am getting the following errors as shown below in iOS only. Could you please help me resolve this. Thanks

<img width="1680" alt="Screenshot 2020-07-07 at 10 04 53 PM" src="https://user-images.githubusercontent.com/50735542/86815418-439ec380-c0a0-11ea-8c8b-d8873351c3b8.png">
<img width="1680" alt="Screenshot 2020-07-07 at 10 06 08 PM" src="https://user-images.githubusercontent.com/50735542/86815464-4f8a8580-c0a0-11ea-9828-f36c6b39acc8.png">

**Comment by kadikraman** [comment] 2020-07-08 18:17
As discussed offline - I'm not completely sure why it's not working for you, and unfortunately 0.51 is quite old so I can't even run it locally anymore.

I hope you can figure this out, but long term, you should consider upgrading to 0.60+. Closing the issue because we don't really support older versions of React Native, but please let us know if you're still having issues with the latest version.

**Closed by kadikraman** 2020-07-08 18:17 UTC
