### ISSUE TITLE
Keyboard not show on auth screen. 

### ISSUE THREAD

**Issue by romreed** [FormidableLabs/react-native-app-auth#429] opened 2019-12-23 16:32 UTC
## Issue
Hi. On android after show auth screen focus on input field but the keyboard does not show automatically.  Users need to click in input again for show keyboard. On ios keyboard show. 

---

## Environment

* **Your Identity Provider**: `IdentityServer 4`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** react-native cli

**Comment by kadikraman** [comment] 2020-01-07 17:03
I can confirm this behaviour, but I don't know why it's happening. Going directly to the [login screen](https://demo.identityserver.io/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fredirect_uri%3Dio.identityserver.demo%253A%252Foauthredirect%26client_id%3Dnative.code%26response_type%3Dcode%26state%3DBKcza9NovbjWztAibu5LpA%26scope%3Dopenid%2520profile%2520email%2520offline_access%26code_challenge%3DgURkYPfIs6Vtji8EjN3UcObpI7_fHrRq--Y79pvij-8%26code_challenge_method%3DS256) does not open the keyboard in either platform.

![android-keyboard-smol](https://user-images.githubusercontent.com/6534400/71911793-4ad62a80-316c-11ea-8b03-c3679e399057.gif)

**Comment by jpdriver** [comment] 2020-01-08 11:07
Thanks for opening this issue. Unfortunately, we can't fix this because the web-based authentication flows are native views which are presented by the underlying AppAuth SDK ([iOS](https://github.com/openid/AppAuth-iOS), [Android](https://github.com/openid/AppAuth-Android)).

Perhaps any changes to forcibly focus on a particular input after loading the web page could be implemented there; although we would advise against this for accessibility reasons as detailed [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus).

As this issue is not something we can address within the React Native bridge, we are closing this issue off.

**Closed by jpdriver** 2020-01-08 11:07 UTC
Labels: can reproduce, help wanted
