### ISSUE TITLE
login with outlook successfully but Redirect Url not working after login successfully - react native 

### ISSUE THREAD

**Issue by Hassanilyas143** [FormidableLabs/react-native-app-auth#287] opened 2019-04-01 13:39 UTC
## Issue
am working on react native app and using react-native-app-auth library login with outlook,
when i run app on ios device then redirect url working fine. 
but when i run app on android device then then login successfully but redirect url not working.
i try this but not work.
manifestPlaceholders = [
                  appAuthRedirectScheme: 'com.googleusercontent.apps.urn:ietf:wg:oauth:2.0:oob'
        ]

**Comment by kadikraman** [comment] 2019-04-01 14:23
Hi - the redirect scheme is the beginning of your OAuth Redirect URL, up to the scheme separator (:) character. In your case, I think it should be `com.googleusercontent.apps`.

**Comment by Hassanilyas143** [comment] 2019-04-01 14:31
> Hi - the redirect scheme is the beginning of your OAuth Redirect URL, up to the scheme separator (:) character. In your case, I think it should be `com.googleusercontent.apps`

Thanx for the reply.
am using this 
appAuthRedirectScheme: 'com.googleusercontent.apps.urn:ietf:wg:oauth:2.0:oob'
but not work.

**Comment by kadikraman** [comment] 2019-04-01 14:33
Could you please try 
```
manifestPlaceholders = [
  appAuthRedirectScheme: 'com.googleusercontent.apps'
]
```

**Comment by Hassanilyas143** [comment] 2019-04-01 14:36
> Could you please try
> 
> ```
> manifestPlaceholders = [
>   appAuthRedirectScheme: 'com.googleusercontent.apps'
> ]
> ```

not working

**Comment by kadikraman** [comment] 2019-04-01 14:39
Did you rebuild the app? This is a native change, so just refreshing the packager won't be sufficient, you'd have to do `react-native run-android` again.

**Comment by Hassanilyas143** [comment] 2019-04-01 14:41
> Did you rebuild the app? This is a native change, so just refreshing the packager won't be sufficient, you'd have to do `react-native run-android` again.

yes i did but nothing.
can i send react-native code ?

**Comment by kadikraman** [comment] 2019-04-01 14:53
If you could create a repo with a minimal example, that would be helpful.

**Comment by Hassanilyas143** [comment] 2019-04-01 14:56
> If you could create a repo with a minimal example, that would be helpful.

yes sure

**Comment by Hassanilyas143** [comment] 2019-04-01 17:35
> > If you could create a repo with a minimal example, that would be helpful.
> 
> yes sure

please have a look i created new demo project for you.
repo:
https://github.com/Hassanilyas143/OutlookTest
its working on ios fine but when i run on android device then login successfully but redirect url not working please help me.
test credentials:
email: Rashdan.devo@outlook.com
password: R@shdand3V

**Comment by kadikraman** [comment] 2019-04-01 18:11
Hi @Hassanilyas143 - I could reproduce your error.

Investigating further, it looks like `urn:ietf:wg:oauth:2.0:oob` was never intended to be used on mobile, and it's a fluke that it even works on iOS. See this comment https://github.com/openid/AppAuth-Android/issues/164#issuecomment-278768826

So what you'll need to do is to register a new redirect on your IDP (something like my.app/oauth2redirect) and use that instead.

I will update our documentation to reflect this as well.

PS! I'm deleting your previous comment due to sensitive info. Even if those aren't your real credentials, you probably don't want to tempt the hackers :)

**Comment by rashdan** [comment] 2019-04-10 15:41
hey @kadikraman 
i am trying to make a new redirect url but could not find the way to do it 
can you explain it !
i am using `https://portal.azure.com/`

**Comment by sultan-arshi** [comment] 2019-04-10 16:21
it is working for me only for  iOS but not for the android 
I am also trying to authentication with outlook 
any body solved it ?
I also can not make new url as @kadikraman told us 
I can not find the way in the azure

**Comment by Jay-A-McBee** [comment] 2022-01-18 18:53
:wave: hey everyone - closing this out as it sounds like an IDP configuration issue.

**Closed by Jay-A-McBee** 2022-01-18 18:53 UTC
