### ISSUE TITLE
linker command failed - ld: library not found for -lAppAuth

### ISSUE THREAD

**Issue by brkrtp** [FormidableLabs/react-native-app-auth#118] opened 2018-06-17 13:12 UTC
<img width="271" alt="screen shot 2018-06-17 at 16 11 00" src="https://user-images.githubusercontent.com/18514716/41508184-2c797eae-7249-11e8-90ad-c6793e34d7ad.png">
<img width="688" alt="screen shot 2018-06-17 at 16 11 05" src="https://user-images.githubusercontent.com/18514716/41508185-2c9a0d2c-7249-11e8-81f4-c3c96d869fe7.png">

```
ld: warning: directory not found for option '-L/Users/brkrtp/Library/Developer/Xcode/DerivedData/burak
-ceqbfdnxrzunipektpsftfekkcjw/Build/Products/Debug-iphoneos/AppAuth'
ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by kadikraman** [comment] 2018-06-19 11:55
Have you run `react-native link`? If you have and you're still getting the error, try running the example app and compare its config to yours on Xcode.

**Comment by ButuzGOL** [comment] 2018-06-26 06:45
same i just open Example from xcode and build it and this error
but if i do with react-native run-ios all good

**Comment by ButuzGOL** [comment] 2018-06-26 07:44
Also i have notice this line
> Include libAppAuth as a linked library for your target (in the "General -> Linked Framework and Libraries" section of your target).

but i cant find libAppAuth

**Comment by kadikraman** [comment] 2018-06-26 10:38
Hmm, I can't reproduce it. Which version of Xcode are you on?

**Comment by ButuzGOL** [comment] 2018-06-26 12:18
Version 9.3
I did a lot of things but those might help
I did two things put 
1. Pods.xcodeproj in libraries
2. did rm -rf ~/Library/Caches/CocoaPods
3. pod install

**Comment by ButuzGOL** [comment] 2018-06-26 12:20
And it helps but any way my ci still fails appcenter
[logs_390.zip](https://github.com/FormidableLabs/react-native-app-auth/files/2137056/logs_390.zip)

**Comment by ButuzGOL** [comment] 2018-06-26 12:33
you can try do git clone from scratch i think you should be able to reproduce

**Comment by ButuzGOL** [comment] 2018-06-26 14:32
currently faced with dev pass but on archive fails with this error

**Comment by ButuzGOL** [comment] 2018-07-03 13:04
i think the problem with xcode version and pod
in latest xcode and lates pod all should be good but i will recheck it

**Comment by kadikraman** [comment] 2018-07-11 15:56
Hi, I've just released `v3.0.0` of this library, which should fix some weirdness with iOS integration. Could you please try again with the latest version? Note that the code you need to add to AppDelegate [has changed](https://github.com/FormidableLabs/react-native-app-auth#define-openurl-callback-in-appdelegate).

**Comment by Jonny993** [comment] 2018-09-13 15:39
updates on this? same error!

**Comment by kadikraman** [comment] 2018-09-13 15:55
@Jonny993 have you run `react-native link`? What version of React Native and this library are you running?

**Comment by Jonny993** [comment] 2018-09-13 16:08
![image](https://user-images.githubusercontent.com/10560006/45500798-ce058d00-b77f-11e8-9eec-2fbfb2efa35e.png)

react-native link done, all is working fine when I run the app in the IOS simulator, but problems comes up when I try to build with xcode!

```"react-native": "0.56.0"
"react-native-app-auth": "^3.1.0"```

Tell me if you need anything else

**Comment by kadikraman** [comment] 2018-09-13 16:35
@Jonny993 are you sure you've opened the`.xcworkspace` file (instead of the `.xcodeproj` which doesn't see pods)?

**Comment by Jonny993** [comment] 2018-09-14 09:08
> @Jonny993 are you sure you've opened the`.xcworkspace` file (instead of the `.xcodeproj` which doesn't see pods)?

If I try to open the workspace I don't have any command for build or anything like that.

However, digging more in the problem I found out that XCODE can't find lib named "AppAuth" in the project, so I went to the folder to see which libraries are builded

![image](https://user-images.githubusercontent.com/10560006/45541059-487cee00-b80e-11e8-81d6-e2ffb836e7c3.png)

As I thought, no "AppAuth" lib is present, so I went in the build settings of the project, I searched for "Search Paths" and found out that for debugging and releasing the "Library Search Paths" was pointing to something "wrong" (AppAuth) so I changed the paths for pointing to the correct named lib but error is the same.

Here you can see

![image](https://user-images.githubusercontent.com/10560006/45541155-8bd75c80-b80e-11e8-9ee8-2091113d5f98.png)

**Comment by Jonny993** [comment] 2018-09-14 10:30
Ok so, huge update!
I reverted all the updates done yesterday and tried to do the following:
- react-native run-ios

Got sured that everything was building and working fine on IOS Simulator

- opened up `.xcworkspace` file instead of `.xcodeproj` one
- this time, I could navigate the xcode project inside the workspace (I couldn't yesterday, don't know why, something was messing up the entire project)
- added team and provisioning profile from `target`, `general` tab
- added iOS Developer from `project`, `Code Signing Identity` to everything

![image](https://user-images.githubusercontent.com/10560006/45545119-a3681280-b819-11e8-9bb8-99c3cfe1b0d3.png)

- build with CMD+R command the app directly on device
- inserted password when prompted
- done!

So just to clarify.. I was having some kind of problems accessing the `.xcworkspace` and so I tried to do the build on the `.xcodeproj`, which gave the errors above. 
Cleaned everything up, restarting from yesterday, following the react native guide on how to build the app on device and boom, everything was working fine

**Comment by kadikraman** [comment] 2018-09-14 10:52
@Jonny993 awesome! 🎉

`.xcworkspace` vs `.xcodeproj` can be super confusing especially if you're new to xcode 😬  - but the rule of thumb in this case is that if you're using pods, you have to open `.xcworkspace`.

Closing this issue as although you weren't the original author of the issue, I get the feeling the solution is the same.

**Closed by kadikraman** 2018-09-14 10:52 UTC

**Comment by chairmin** [comment] 2019-05-14 11:34
> @Jonny993 are you sure you've opened the`.xcworkspace` file (instead of the `.xcodeproj` which doesn't see pods)?

thanks

**Comment by vymallesh** [comment] 2019-05-20 14:47
Hey,

I was facing same kind of issue with Microsoft Outlook login SDK integration.I was using Cocoapods to install the libraries.I am getting below error,

ld: library not found for -lMSGraphSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FYI : Podfile is   : pod 'MSGraphSDK'
 pod 'MSGraphSDK-NXOAuth2Adapter'  and XCode version is 10.2.1

Any help would be appreciated !!
Thanks.

**Comment by lguardado** [comment] 2019-07-25 20:54
> Ok so, huge update!
> I reverted all the updates done yesterday and tried to do the following:
> 
> * `react-native run-ios`
> 
> Got sured that everything was building and working fine on IOS Simulator
> 
> * opened up `.xcworkspace` file instead of `.xcodeproj` one
> * this time, I could navigate the xcode project inside the workspace (I couldn't yesterday, don't know why, something was messing up the entire project)
> * added team and provisioning profile from `target`, `general` tab
> * added `iOS Developer` from `project`, `Code Signing Identity` to everything
> 
> ![image](https://user-images.githubusercontent.com/10560006/45545119-a3681280-b819-11e8-9bb8-99c3cfe1b0d3.png)
> 
> * build with CMD+R command the app directly on device
> * inserted password when prompted
> * done!
> 
> So just to clarify.. I was having some kind of problems accessing the `.xcworkspace` and so I tried to do the build on the `.xcodeproj`, which gave the errors above.
> Cleaned everything up, restarting from yesterday, following the react native guide on how to build the app on device and boom, everything was working fine

Thank you! it worked for me!!

**Comment by lguardado** [comment] 2019-07-25 20:54
Thank you @Jonny993! it worked for me too!

**Comment by voold** [comment] 2020-04-28 21:49
I still get the same error. I tried everything. It has been a day I'm on this. Please can you help? The solution above did'nt help
