### ISSUE TITLE
authorize() returns error 'Data intent is null' on Android

### ISSUE THREAD

**Issue by KristineTrona** [FormidableLabs/react-native-app-auth#494] opened 2020-04-01 13:05 UTC
## Issue

Every time I call ``authorize()`` method I get ``Error: Data intent is null``, whenever running on an Android emulator with 'R' operating system. Any idea what could be causing this error and how to fix it?

```
const config = {
  warmAndPrefetchChrome: Platform.OS === 'android',
  issuer,
  clientId,
  redirectUrl: 'testSchema://oauth/redirect',
  scopes: ['openid', 'profile', 'api', 'offline_access'],
  usePKCE: true,
};

export const authenticate = async () => {
  try {
    const result = await authorize(config);
    console.log('authorized')  // Execution never makes it to this line
    return result
  } catch (e) {
    throw new Error(e);
  }
};
```

In android/app/builde.gradle

```

    defaultConfig {
        applicationId "com.testApp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
        resValue "string", "build_config_package", "com.testApp"
        manifestPlaceholders = [
            appAuthRedirectScheme: 'testSchema'
        ]

    }
```

AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.testApp">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".SplashActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
      </activity>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <provider
		    android:name="com.vinzscam.reactnativefileviewer.FileProvider"
		    android:authorities="${applicationId}.provider"
		    android:exported="false"
		    android:grantUriPermissions="true">
		    <meta-data
		    	android:name="android.support.FILE_PROVIDER_PATHS"
		    	android:resource="@xml/file_viewer_provider_paths"
		    />
	    </provider>
    </application>

</manifest>
```

Fails on all 3 of these, but works fine on 'Q' or 'Pie' operating systems:
<img width="857" alt="Screenshot 2020-04-02 at 15 23 22" src="https://user-images.githubusercontent.com/39855778/78254240-e5d56b00-74f5-11ea-851b-9c109353175b.png">

## Environment

* **Your Identity Provider**: IdentityServer 4 
* **Platform that you're experiencing the issue on**: Android (specific to version 'R')
* **Are you using Expo?** No

**Comment by KristineTrona** [comment] 2020-04-02 09:05
FYI, I've also tried to do this in a completely fresh project now, but still the same error.

**Comment by thilinawarnakula** [comment] 2020-04-09 09:38
@KristineTrona did you find a fix to this

**Comment by KristineTrona** [comment] 2020-04-09 09:47
@thilinawarnakula no, but I think it happens only on Android 11.0.0 (R), which has not been released to the public yet.

**Comment by Shpadoinkle** [comment] 2020-07-02 01:02
@KristineTrona  Hi Kristine, 
Did you end up solving this issue?

**Comment by KristineTrona** [comment] 2020-07-02 06:30
Hi, no, unfortunately I did not.

**Comment by Shpadoinkle** [comment] 2020-07-02 08:03
Not sure if it will help others,
But our issue was a double up of the redirectUrl, the documentation mentions two places you can put it.  In the build gradle or manifest..  But you can only do one or the other. 
Putting it in both places is what broke it for us.

**Comment by harunsmrkovic** [comment] 2020-08-03 13:58
I resolved this by adding the link prefix into the build.gradle file

```
manifestPlaceholders = [
            appAuthRedirectScheme: 'com.mobileubdiapp',
            appAuthRedirectScheme: 'ubdi'
        ]
```

e.g. If the redirect URL is `ubdi://connect`, then you need to have `ubdi` listed here

**Comment by kadikraman** [comment] 2020-08-13 13:30
Thank you for posting your solution @Shpadoinkle and @harunsmrkovic !

@KristineTrona Is this still an issue for you? I can't reproduce this on my emulator. This is the Example app with the Identity Server 4 configuration running on Pixel 2 with API 30.

![Screenshot 2020-08-13 at 14 29 30](https://user-images.githubusercontent.com/6534400/90140292-7019bf80-dd71-11ea-892c-b93314164709.png)

![android](https://user-images.githubusercontent.com/6534400/90139886-da7e3000-dd70-11ea-8034-fe093157cbb3.gif)

**Comment by aliiqbal436** [comment] 2020-09-17 11:38
I am facing this same issue.

**Comment by adailson2** [comment] 2020-09-23 03:17
I have the same issue and I tried all solutions in this thread, but I have not success.

**Comment by sharadkatre1995** [comment] 2020-10-01 08:45
I am also facing the same issue did anyone gets anything.
Thanks

**Comment by AlkanV** [comment] 2020-10-21 09:18
i am facing same issue

**Comment by yberstad** [comment] 2020-11-17 14:18
From our production logs I see that some of our customers are getting this error, but I'm having a hard time reproducing the error. Does anyone have an "recipe" how to reproduce this error?

I have tried to use these steps to reproduce it, but no luck https://github.com/FormidableLabs/react-native-app-auth/issues/130#issuecomment-510392495

(Our app is using android:launchMode="singleInstance" instead of android:launchMode="singleTask", not sure if this has anything to do with this error)

**Comment by AlkanV** [comment] 2020-11-17 14:25
Hello @yberstad ,

the problem here is that, react-native-app-auth is not getting data from redirectUri. this is caused because of wrong configuration in intents.
below you can find how i get rid of this error.

```
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter android:label="@string/app_name">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
       <data android:scheme="your.deeplink.scheme" />
      </intent-filter>
    </activity>
	<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="your.deeplink.scheme.for.oauth"  />
    </intent-filter>

```
basically, rn-app-auth gets data from `redirectUri` via deeplink. so you need to configure rn-app-auth to look correct deep linking scheme.

```js
// in build.gradle
defaultConfig{
...
manifestPlaceholders = [
            appAuthRedirectScheme: 'nativevideo1'
        ]
}
```

**Comment by yberstad** [comment] 2020-11-18 06:18
@AlkanV thank you so much for your very quick response, much appreciated!

This is our current config:
```
{
  issuer: https://identity-dev.sharpnet.no,
  clientId: "sharpnetapp",
  redirectUrl: "sharpnet://signin-oidc",
  scopes: ["openid", "appdevice", "applogin"],
  additionalParameters: {}
};
```

/app/build.gradle:

```
manifestPlaceholders = [
    appAuthRedirectScheme: 'sharpnet'
]
```

And here is our current intent-filter's in AndroidManifest.xml:
```
<activity
    android:name=".MainActivity"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
    android:label="@string/app_name"
    android:theme="@style/SplashTheme"
    android:launchMode="singleInstance"
    android:windowSoftInputMode="adjustResize">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
    </intent-filter>
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
    </intent-filter>
</activity>
```


Should I change it to this?
```
<activity
    android:name=".MainActivity"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
    android:label="@string/app_name"
    android:theme="@style/SplashTheme"
    android:launchMode="singleInstance"
    android:windowSoftInputMode="adjustResize">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
    </intent-filter>
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="sharpnet" />
    </intent-filter>
</activity>
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="sharpnet"  />
    </intent-filter>
</activity>
```

Just a clarification, we are only getting "Data intent is null" for some our Android users. It is working for the majority of our users.

**Comment by netanelh** [comment] 2020-12-22 12:45
@yberstad did you find why it happens only to **some** users?

**Comment by yberstad** [comment] 2021-01-06 09:17
@netanelh sorry, did not see your post before now. 

No, we have not figured this out yet. I have been able to reproduce the error (but not in a way I think the user does it):

1. Open the app
2. Start the authentication process (oidc web page)
3. Press home button
4. Open the app again
5. Then I get the "Data intent is null"

I suspect that this is due to that we get a new instance of the app (using android:launchMode="singleInstance") and that the original intent is lost?

If i look in node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java I see this code:
`@Override
public void onNewIntent(Intent intent) {
}`

The new intent is not "saved", but I do not know if this has anything to do with? Again, I do not think this is what the users experiencing this error is actually doing. 

I anyone have some new insights on this issue, it would be much appreciated!

**Comment by DanielSchwartz89** [comment] 2021-01-14 07:57
Any possible solution or workaround? @yberstad

**Comment by yberstad** [comment] 2021-01-14 08:43
@DanielSchwartz89, not to my knowledge unfortunately.

**Comment by Aleksefo** [comment] 2021-02-02 19:49
We have exactly the same issue in our project. @yberstad your reproduction steps are correct.

To trigger "Data intent is null" error, the user must:
1. Open the app
2. Start the authentication process (web page)
3. Press home button
4. Open the app again (**through Home screen icon**)
5. Then the webview is automatically closed and the user sees the error.

To avoid the issue, the user, during step 4, must use Recent apps/Overview button/gesture to navigate back to the app.

For some reason, there is a difference in app-auth behavior depending on the user opening the app through the Home screen or Recent apps. One case always fails, the other succeeds. 

We suspect it is due to onResume() method triggering finish() in AuthorizationManagementActivity.java of AppAuth-Android.
https://github.com/openid/AppAuth-Android/blob/907ebbd890738e47c0c0c5d04fc6dfa6c449891b/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L211

The issue is quite critical since in our case we need to use third-party banking apps to authenticate, so the users have to switch between apps. At the moment we have to manually instruct the users to use "Recent apps" instead of the home button, but that is not a good solution.

**Comment by Aleksefo** [comment] 2021-02-03 17:13
The fix seems to be to change android:launchMode to "singleTop" in AndroidManifest.xml

**Comment by yberstad** [comment] 2021-02-05 10:53
@Aleksefo, thank you so much for your info, very helpful! 

I was initially sceptic to change the android:launchMode, because I was not sure what implications it could have. 

But after trying to grasp the concept, I cannot see that would have any implications to change it (especially since we only have one activity in our RN application). 

I watched the series regarding the concept of lauchMode, https://www.youtube.com/watch?v=gRub-Pm_A0Q&t=36s, which was very helpful.

**Comment by Aleksefo** [comment] 2021-02-05 11:53
@yberstad I've noticed some issues with this approach though:
If the app is opened from Google play(install then open), then the first Bank login(where you have to navigate between apps) fails. Follow up logins are successful using the "home screen icon" method. (That's the issue with android:launchMode )
The same scenario but using "recent apps" instead of "home screen icon" succeeds as before.
If the app is opened for the first time from home screen, then everything works no matter what.
If the app is opened from Google play, but the user logins with Email(no need for switching apps), then all works.

We also have a bank which prompts a user for extra input after the authentication.
It is more unpredictable(probably due to an extra step).
When user returns(with "home screen icon") to the app it shows RN part instead of the webview. If the user clicks the Android back button, then the bowser is shown with extra final step of authentication. (That's the issue with android:launchMode )
After clicking authenticate, the user is shown the RN part again, but login showed as failed.
If the user closes the app and opens it again, they are authenticated and everything works.

So overall I think it's a big win, since it doesn't affect successful logins, but fixes previously unsuccessful login almost without issues.

**Comment by yberstad** [comment] 2021-02-05 11:59
@Aleksefo, thanks for a nice summary of various use cases. I'll bring that with me while testing our app 😄

**Comment by Aleksefo** [comment] 2021-02-05 12:09
@yberstad Sure, let me know if you'll find any extra issues.

I think the next step would be to modify either react-native-app-auth or app-auth-android to disable onResume() methods breaking the authentication and then apply a custom patch to get rid of the issue for good.
"android:launchMode" is more of a hack than a long term solution, so fixing the issue directly would be preferable.

**Comment by yberstad** [comment] 2021-02-05 15:41
@Aleksefo, I'll definitely get back to you if I find some issues regarding this! Again, thanks for letting me know of your findings!

**Comment by Aleksefo** [comment] 2021-02-19 13:55
The issue is not related to Auth library, but android in general: https://issuetracker.google.com/issues/36907463
Final solution:

AndroidManifest.xml:
android:launchMode="standard"

MainActivity.java
```
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    if (!isTaskRoot()) {
      finish();
      return;
    }
  }
```

The fix works in most of the cases except when the app is opened from an unusual source (react-native start, Google play, etc.). In that case, using home screen icon to return to the app will cause extra activity on top of the stack which cannot be removed using something like React Navigation, for example.
It might be possible to write a native module with a function to close the activity. The solution I made is this function to close the app if the user successfully authenticated, but the login screen is shown again on that extra activity. The app is closed, but the next time you open it, the app will be authenticated already.

Somewhere where you have login button:
```
    const onPress = () => {
      if (accessToken && Platform.OS === "android") {
        sendEvent({
          event_name: "onboarding_exitApp_pressed",
        });
        BackHandler.exitApp();
      } else {
        login();
      }
    }
```

**Comment by badsyntax** [comment] 2021-03-12 10:27
It seems this ticket is diverging into different issues. The issue I'm referring to is the `Error: Data intent is null` error.

The problem I experienced was due to having deeplink integration already in place, using [reactnavigation](https://reactnavigation.org/).

You won't see this issue if you have not defined other intent-filters for the same auth scheme.

Based on the [reactnavigation instructions](https://reactnavigation.org/docs/deep-linking/#android), I have the following set in my `AndroidManifest.xml`:

```xml
<activity
  android:name=".MainActivity"
  android:label="@string/app_name"
  android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
  android:launchMode="singleTask"
  android:windowSoftInputMode="adjustResize">
  <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
  <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="com.myapp" />
  </intent-filter>
</activity>
```

And for `react-native-app-auth`, I have set the following in my `build.gradle`:

```groovy
android {
    defaultConfig {
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.myapp'
        ]
    }
}
```

Note that adding the above effectively is the same as explicitly adding a new activity & intent filter like so:

```xml
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.myapp"/>
    </intent-filter>
</activity>
```

So now we have two activities handling the same scheme.

The result of this is that after logging in, I'm presented with an "Open With" prompt that shows my app twice. I assume because there are now effectively two `intent-filter`'s for the same scheme. 

If I select the app that's handling the `.MainActivity` activity, I get the `Error: Data intent is null` error. If I select the other app, the authentication works.

To "fix" this, I followed @AlkanV's [advice](https://github.com/FormidableLabs/react-native-app-auth/issues/494#issuecomment-728962072) and used a different scheme for the authentication redirect url, set in the build.gradle:

```groovy
android {
    defaultConfig {
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.myapp.auth'
        ]
    }
}
```

I then updated my redirect url to reflect the auth redirect scheme. After logging in, everything works. I don't get the "open with" prompt and I don't get the auth error. I don't like that the app handles two different deeplinking schemes, but I'm not sure if this is a problem or not. 

I will create a new ticket asking the library authors to update the example to include reactnavigation.

**Comment by activebiz** [comment] 2021-03-12 14:56
This is still issue for me and problem is that its only happending on some android devices!

**Comment by ahaus** [comment] 2021-04-27 09:10
Just want to leave a note here because I was led into the wrong direction with the error message 'Data intent is null'.
We had this problem with our app after we updated to Android 11.  
The problem was not the app but we had to accept the user (google play user ...) again when opening Google Chrome. This also prevented this library to open up a Google Chrome Tab properly to initiate the login process. After this the login process again worked again as expected.

**Comment by pke** [comment] 2021-05-06 13:31
Could this please be fixed? It does not make much sense to me, why a different theme would be required for iOS and Android.
Can't the browser frame RNappAuth opens not listen to the redirect URI? Why does it have to a new activity with a different scheme than in the iOS app?

**Comment by anisimov74** [comment] 2021-09-22 13:15
It's inconvenient to have different schemes, because we have to add this additional scheme on the server side.

**Comment by anisimov74** [comment] 2021-09-23 09:35
@badsyntax could you please clarify what exact configuration do you have in Manifest.xml?
I tried both `appAuthRedirectScheme: 'com.myapp.oauth'` with and without intent
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.myapp"/>
    </intent-filter>
</activity>
```
The redirect URL is `com.myapp.oauth://landing.url` 
**I'm not been redirected back into the app**.

I have the following intent, related to deep linking
```
<intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="com.myapp"/>
</intent-filter>
```

**Comment by badsyntax** [comment] 2021-09-23 13:12
@anisimov74 i can't share my manifest file as it contains a bunch of other activities and it will just confuse others. I can say that instead of using `appAuthRedirectScheme ` I ended up explicitly adding the `RedirectUriReceiverActivity` activity into my AndroidManifest.xml:

```xml
<activity
  android:name="net.openid.appauth.RedirectUriReceiverActivity"
  tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.example.app.auth"/>
    </intent-filter>
</activity>
```

I see you've tried the same, but your sheme looks wrong to me. Should `com.myapp` be `com.myapp.oauth`?

**Comment by anisimov74** [comment] 2021-09-23 13:14
@badsyntax thank you for the quick response. I just typed a wrong string. It's definitely `com.myapp.oauth`.

**Comment by badsyntax** [comment] 2021-09-23 13:22
@anisimov74 what do you mean you can't make a project? What is the error?

**Comment by anisimov74** [comment] 2021-09-23 13:41
@badsyntax that seems to be some sort of cache problem. After switching between branches, that error has gone.
I have the only change in Manifest.xml.
Still no redirect. Any thoughts?
```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
        <intent-filter>
          <action android:name="android.intent.action.VIEW"/>
          <category android:name="android.intent.category.DEFAULT"/>
          <category android:name="android.intent.category.BROWSABLE"/>
          <data android:scheme="com.mobile.app.oauth" android:host="landing.url"/>
        </intent-filter>
      </activity>
```

**Comment by badsyntax** [comment] 2021-09-23 13:45
@anisimov74 does the `redirectUrl` in the config you pass to `authorise()` match the scheme?

**Comment by anisimov74** [comment] 2021-09-23 13:48
@badsyntax yes it is. It's `com.mobile.app.oauth://landing.url`

**Comment by anisimov74** [comment] 2021-09-23 13:50
@badsyntax and I see that in logs
```
2021-09-23 15:49:06.940 2046-2449/? I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=com.mobile.app.oauth://landing.url?code=XXXXXXXXXXXXXX flg=0x14000000 cmp=com.jetbrains.youtrack.mobile.app/net.openid.appauth.RedirectUriReceiverActivity (has extras)} from uid 10114
```

**Comment by badsyntax** [comment] 2021-09-23 13:54
Can you try without the landing.url host? So remove `android:host="landing.url"`. That's really the only difference I can tell. When you say "still no redirect", what exactly is happening after you authenticate?

**Comment by anisimov74** [comment] 2021-09-23 14:22
@badsyntax tried without `android:host="landing.url`. After entering credentials I see a Chrome tab.

**Comment by badsyntax** [comment] 2021-09-23 14:36
I'm out of ideas. IMO it would be useful if this repo has a reactnavigation example that people can refer to.

**Comment by anisimov74** [comment] 2021-09-23 14:38
@badsyntax thank you for helping me! Will try more variants.

**Comment by anisimov74** [comment] 2021-09-23 14:51
@badsyntax the last question. How is look like your redirectUrl param? Does it matter what is the after `://`?
`com.mobile.app.oauth://oauth` or `com.mobile.app.oauth://oauth.url`?

**Comment by anisimov74** [comment] 2021-09-29 14:36
I figured out the cause of the problem. There is a In Manifest.xml `android:taskAffinity=""`. Which should prevent possible phishing via task hijacking.

**Comment by Willian-Rodrigues** [comment] 2021-12-29 14:49
1
change package name in redirectUrl
com.YOUR_APP => com.YOUR_APP.auth

```
const config = {
      issuer: 'https://accounts.google.com',
      clientId: 'YOUR_clientId',
      redirectUrl: 'com.YOUR_APP.auth:/oauth2callback', 
     scopes: ['email', 'profile'],
};
```

2
change the package name on the google website
com.YOUR_APP => com.YOUR_APP.auth

3
in `build.gradle`
```
android {
    defaultConfig {
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.YOUR_APP.auth'
        ]
    }
}
```

**Comment by Jay-A-McBee** [comment] 2022-01-24 21:32
Closing this due to subject drift - sounds like a configuration issue. Creating redundant intent handlers by using both the manifest and manifestPlaceholders in build.gradle.

**Closed by Jay-A-McBee** 2022-01-24 21:32 UTC

**Comment by mrjosshi** [comment] 2022-08-24 08:49
Any update on this ?

**Comment by zeinabzahran** [comment] 2022-09-13 11:56
Same issue. Any updates?

**Comment by xenialugovaya** [comment] 2022-11-18 16:39
Same issue, double checked configuration. Has anyone figured out how to fix this?

**Comment by RubenPM-dev** [comment] 2023-01-18 15:22
I had this issue recently and it turns out I was using characters on my scheme that are not allowed, such as ' / '.

Fount some useful information about this on this Flutter rep:
[https://github.com/LinusU/flutter_web_auth#troubleshooting](url)

**Comment by witherBattler** [comment] 2023-02-12 15:37
I have this issue as well

**Comment by AbbasTheReckoner** [comment] 2023-04-07 12:28
> I resolved this by adding the link prefix into the build.gradle file
> 
> ```
> manifestPlaceholders = [
>             appAuthRedirectScheme: 'com.mobileubdiapp',
>             appAuthRedirectScheme: 'ubdi'
>         ]
> ```
> 
> e.g. If the redirect URL is `ubdi://connect`, then you need to have `ubdi` listed here

can we add multiple redirectSchemes to manifestplaceholder  @harunsmrkovic ?

**Comment by avinash-capsitech** [comment] 2023-09-13 13:02
i'm getting same issue Data intent is null any solution ??

**Comment by 4RGUS** [comment] 2023-09-18 13:02
I also tried all of the solutions above and still I have the same issue.

**Comment by avinash-capsitech** [comment] 2023-09-18 13:21
i resolved this by following steps:--

1. **Remove manifestPlaceholders from build.gradle(Module:app).**
```
defaultConfig {
        applicationId "com.dummy"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
//        manifestPlaceholders = [
//                appAuthRedirectScheme: 'com.gumtestapp',
//                appAuthRedirectScheme: 'ao'
//        ]
    }
```
2. **Changes in manifest :** 

**Add to application tag :**
```
<activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="your_scheme"/>
            </intent-filter>

        </activity> 
```

**Remove from main activity:**
  ```
<intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="your_scheme"/>
            </intent-filter>
```

**Comment by salonikale9** [comment] 2024-10-10 12:35
i am also facing issue of data intent but i solve just by changing         <data android:scheme="your.schema"/> instead of     <data android:scheme="your.schema" android:host="auth" /> my issue is resolve.

**Comment by JaskirtKaler** [comment] 2024-10-26 22:32
@badsyntax were you able to get the Authentication to return the access tokens currently the redirect link pops up for Android env but does not return back to the app. However, it does show in the AD sign-in logs that a user signed in and it was successful. not exactly sure what is going wrong

**Comment by nicodelac** [comment] 2024-11-11 15:06
Anyone found out a workaround? Tried all of the solutions above and still I have the same issue...

React native v0.63.2
React native auth app v5.1.0
React native web view v13.12.3

**Comment by HarveyNgo** [comment] 2025-08-08 11:52
In my case: i using keycloak with Expo and react-native-auth

android {
    defaultConfig {
        manifestPlaceholders = [appAuthRedirectScheme:"abc-keycloak"]
   }
}

------------------------------------------
here is redirect URI in keycloak admin:

<img width="1091" height="103" alt="Image" src="https://github.com/user-attachments/assets/a0a29ca5-0d4a-44bf-8aa5-9b24fb3ab581" />

------------------------------------------
more important I forgot add clientSecret in config:
<img width="396" height="140" alt="Image" src="https://github.com/user-attachments/assets/40b0275b-b556-4240-8c39-0cf6eef6ff34" />

**Comment by Devanshuji** [comment] 2025-08-19 04:15
Hey I found the solution by extending the native modules with the new react native version 0.80.2 I just uses the custom native modules

**Comment by DhruvKalpeshThakar** [comment] 2025-11-25 13:07
> Not sure if it will help others, But our issue was a double up of the redirectUrl, the documentation mentions two places you can put it. In the build gradle or manifest.. But you can only do one or the other. Putting it in both places is what broke it for us.

Don't Know If Anybody Paid Attention Here, But This Actually Worked, Thanks!
